name: AI Comment Reply Assistant

on:
  # PRの差分レビューコメントが作成されたときにトリガー
  pull_request_review_comment:
    types: [created]

jobs:
  reply_to_comment:
    # コメント投稿者がボットの場合、無限ループを防ぐためにワークフローを実行しない
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # コメントが付けられた時点のコミットをチェックアウト
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests google-generativeai

      - name: Run AI Reply Script
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # イベントから必要な情報をPythonスクリプトに渡す
          COMMENT_BODY: ${{ github.event.comment.body }}
          COMMENT_ID: ${{ github.event.comment.id }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          FILE_PATH: ${{ github.event.comment.path }}
          COMMIT_ID: ${{ github.event.comment.commit_id }}
          START_LINE: ${{ github.event.comment.start_line }}
          END_LINE: ${{ github.event.comment.line }}
        run: python reply_script.py # このPythonスクリプトを別途作成する必要がある